### ISSUE TITLE
Comparison of integer expressions of different signedness

### ISSUE THREAD

**Issue by sounddroid** [IRT-Open-Source/libbw64#11]
Hello! Using gcc 9.1.0, I'm getting a few compiler warnings:

In **reader.hpp**:

Line **220**: 
`if (frameOffset < 0 && dataChunkOffset < -frameOffset) {`
*warning: comparison of integer expressions of different signedness: 'uint64_t' {aka 'long unsigned int'} and 'int64_t' {aka 'long int'} [-Wsign-compare]

Line **225**:
`if (fileStream_.tellg() < chunkPosition) {`
*warning: comparison of integer expressions of different signedness: 'std::streamoff' {aka 'long int'} and 'uint64_t' {aka 'long unsigned int'} [-Wsign-compare]

Line **227**:
`} else if (fileStream_.tellg() > chunkPosition + dataChunk()->size()) {`
*comparison of integer expressions of different signedness: 'std::streamoff' {aka 'long int'} and 'uint64_t' {aka 'long unsigned int'} [-Wsign-compare]

Any chance that this can get looked at and addressed safely?

**Comment by bluetarpmedia** [comment]
This should fix them:

`if (frameOffset < 0 && dataChunkOffset < static_cast<uint64_t>(-frameOffset)) {`

and

```
const auto fileStreamPos = fileStream_.tellg();
if (fileStreamPos < 0)
  throw std::runtime_error("fileStream::tellg failed");
if (static_cast<uint64_t>(fileStreamPos) < chunkPosition) {
  fileStream_.seekg(chunkPosition);
} else if (static_cast<uint64_t>(fileStreamPos) > chunkPosition + dataChunk()->size()) {
  fileStream_.seekg(chunkPosition + dataChunk()->size());
}
```
