### ISSUE TITLE
SampleRate parameter in bw64 constructor is uint16

### ISSUE THREAD

**Issue by smlehbleh** [IRT-Open-Source/libbw64#13]
Hi, I noticed when writing out 96khz audio data that the samplerate metadata in the .wav file ended up wrong - looks like the culprit is the samplerate parameter being passed into the Bw64Writer constructor as a 16-bit unsigned int. I think in the bw64 helper wrapper function there is the same issue.

https://github.com/IRT-Open-Source/libbw64/blob/3a43f909f7e8f6bef93403816e9b73b8bfa5a133/include/bw64/writer.hpp#L49

**Comment by benjamin-weiss** [comment]
Thanks for the bug report. Could you have a look at this PR https://github.com/IRT-Open-Source/libbw64/pull/14

**Comment by smlehbleh** [comment]
PR looks good thanks
