### ISSUE TITLE
Bw64Writer under reports riff chunk size by 4 bytes.

### ISSUE THREAD

**Issue by rsjtaylor** [IRT-Open-Source/libbw64#4]
According to [microsoft](https://docs.microsoft.com/en-us/windows/desktop/xaudio2/resource-interchange-file-format--riff-) 

> The value of fileSize includes the size of fileType FOURCC plus the size of the data that follows, but does not include the size of the "RIFF" FOURCC or the size of fileSize.

i.e. it's the size of the chunk including the header, less eight bytes (4 for "RIFF", 4 for fileSize). The riffChunkSize() method on line 183 of writer.hpp appears to calculate the value as the size of the chunk less twelve bytes, leading to a 4 byte error.

**Comment by mikedevnull** [comment]
fixed by #5
