### ISSUE TITLE
Bug in decodePcmSamples()

### ISSUE THREAD

**Issue by AndrewDowning** [IRT-Open-Source/libbw64#9]
Looks like copy pasta error on 24 bit decode. Should be as follows:

      } else if (bitsPerSample == 24) {
        for (uint64_t i = 0; i < numberOfSamples; ++i) {
          int32_t sampleValue =
              (inBuffer[i * bytesPerSample + 2] & 0xff) << 16 |
              (inBuffer[i * bytesPerSample + 1] & 0xff) <<  8 |
              (inBuffer[i * bytesPerSample    ] & 0xff);
          outBuffer[i] = sampleValue / 2147483647.f;
        }

**Comment by AndrewDowning** [comment]
Oops,  should be /  8388607.  at end too.

**Comment by AndrewDowning** [comment]
Oh damn, and the 16 bit decode should have / 32767.f, not 32768.f, to be consistent with encode.

**Comment by AndrewDowning** [comment]
OK, Ignore me, apart from that last thing about the 16 bit.
I was wrong about the 4bit part, because it was doing that to get the sign right,

**Comment by benjamin-weiss** [comment]
So we can close this issue?
